### ISSUE TITLE
Layer.connect is not a function

### ISSUE THREAD

**Issue by nnmer** [leejms/react-native-layerkit#2]
Hi,

Trying to get it work, but getting `Layer.connect is not a function`.
following the manual added pod etc...
then:

```
const CONFIG = require('./config') ;
const Layer = require('react-native-layerkit');
Layer.connect(
    CONFIG.LAYER.APP_ID,
    (error, success) => {
        if (error) {
            console.log('login error',error);
            //go to main screen
        }
        else {
            console.log('connect success',success);
            //handle error
        }
    }
)
```

what is wrong?

**Comment by nlively** [comment]
Have you properly linked the React Native LayerKit project in XCode?

**Comment by nnmer** [comment]
i think so. did everything as said in the manual.

rn is v0.27.2

**Comment by ranpaco** [comment]
I have the same problem, any updates?

_reactNativeLayerkit2.default.connect is not a function

**Comment by ranpaco** [comment]
Fix with

import { RNLayerKit } from 'react-native-layerkit';
